### ISSUE TITLE
Naming the Community Group

### ISSUE THREAD

**Issue by una** [CSS-Next/css-next#1]
Last week, we resolved to rename the "CSS4 Community Group" since this name was not fully inclusive of the group purpose, which likely includes identifying future levels such as CSS5 as well. Starting an issue to brainstorm some naming ideas (temporarily CSS-Next).

**Comment by jkumara** [comment]
What do you think about: "CSS Versioning Group"

**Comment by GooBall** [comment]
> What do you think about: "CSS Versioning Group"

I was thinking along the same lines. 

I think the biggest risk with a name would be the implication of input into the technical CSS spec - as it will only confuse people. But "CSS Versioning" makes it very clear and a lot harder to misinterpret.

That said... I'm sure people will still get confused and ask for CSS features 😅 What can ya do!

**Comment by argyleink** [comment]
CSS Version Control Group?
CSS Revision Group?

**Comment by jkumara** [comment]
@argyleink I like both. Maybe "CSS Version Control Group" a little better because it sounds more explicit to me.
