### ISSUE TITLE
Will dynamic CSS usage rules be come true?

### ISSUE THREAD

**Issue by onkenut** [CSS-Next/css-next#107]
it just like this:
 .text {
            text-align: right;
             font-size: 14pt; 
        }
        \<div  class="text"> \</div>，
       \<div class="text(null,20)"> \</div>,
      \<div class="text(center,null)" > \</div>,
      \<div class="text(center,20)"> \</div>,
      \<div class="text(font-size=20)"> \</div>

**Comment by argyleink** [comment]
looks like you're wanting custom CSS functions, [check this out](https://css.oddbird.net/sasslike/mixins-functions/).
