### ISSUE TITLE
Need a site to host this groups definitive names 

### ISSUE THREAD

**Issue by argyleink** [CSS-Next/css-next#3]
This would let other sites around the web, reference the canonical list of what properties fit into which name.

**Comment by Que-tin** [comment]
[List of Features](https://docs.google.com/spreadsheets/d/1CPV_BwVdZb8yOvsx-AYhwuIVRcFZ4o4htqnSCnZUE-k/edit?resourcekey=0-lbyzWof4EXdz-k5SsYoTjA#gid=0)
