### ISSUE TITLE
@font-palette-values

### ISSUE THREAD

**Issue by argyleink** [CSS-Next/css-next#71]

**Comment by foolip** [comment]
Is this specifically about the `@font-palette-values` rule, or about the whole `font-palette` feature, including animating it?

**Comment by argyleink** [comment]
specifically values, like color parameters

**Comment by foolip** [comment]
The source of my confusion is that I think of these as a single feature, shipped at the same time:
https://developer.mozilla.org/en-US/docs/Web/CSS/font-palette#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-palette-values#browser_compatibility
