### ISSUE TITLE
How do we track individual property values?

### ISSUE THREAD

**Issue by Que-tin** [CSS-Next/css-next#89]
We currently only track individual properties, but in some cases we have property values that belong into different buckets. One example for this would `text-wrap: pretty` and `text-wrap: balance`. That came out way after `text-balance`.

How and where do we track those special cases?

**Comment by argyleink** [comment]
[`revert-layer`](https://developer.mozilla.org/en-US/docs/Web/CSS/revert-layer)

**Comment by argyleink** [comment]
- logical float values
- logical text align values
- `clip` value for overflow
